# Generated by Django 3.2.6 on 2021-08-22 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_rename_auther_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='auther_image',
            new_name='auther_photo',
        ),
    ]
