# Generated by Django 3.2.6 on 2021-08-22 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storages', '0002_rename_shelf_storage'),
        ('topics', '0001_initial'),
        ('authors', '0002_rename_auther_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('book_image', models.ImageField(blank=True, upload_to='book_image/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_author', to='authors.author')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_storage', to='storages.storage')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_topic', to='topics.topic')),
            ],
        ),
    ]
