# Generated by Django 3.2.6 on 2021-08-22 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_image',
            new_name='book_photo',
        ),
    ]
