# Generated by Django 3.2.6 on 2021-08-23 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_rename_auther_image_author_auther_photo'),
        ('topics', '0002_alter_topic_name'),
        ('books', '0003_rename_book_image_book_book_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='authors.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_photo',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic', to='topics.topic'),
        ),
    ]
