# Generated by Django 3.2.6 on 2021-08-23 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0004_alter_storage_storage_type'),
        ('books', '0004_auto_20210823_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage', to='storages.storage'),
        ),
    ]
