# Generated by Django 3.2.6 on 2021-08-24 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_topic_name'),
        ('storages', '0004_alter_storage_storage_type'),
        ('authors', '0003_rename_auther_image_author_auther_photo'),
        ('books', '0005_alter_book_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='author', to='authors.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='storage',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage', to='storages.storage'),
        ),
        migrations.AlterField(
            model_name='book',
            name='topic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='topic', to='topics.topic'),
        ),
    ]
