# Generated by Django 3.2.6 on 2021-08-22 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shelf',
            new_name='Storage',
        ),
    ]
