# Generated by Django 3.2.6 on 2021-08-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0003_alter_storage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='storage_type',
            field=models.CharField(max_length=10),
        ),
    ]
